<div class="center">
  <div class="content rounded shadow">
    <p class="content_title">Quem Somos</p>
    
    <span class="adver">
      <p>
      O site Anúncio Mosaico é um projeto independente e tem como meta, atingir o maior número de marcas registradas divulgando imagens e URLs de qualquer tipo de anúncio publicado pelos usuários. Nosso objetivo é aprimorar e inovar a tecnologia do site, para que todos os usuários possam  aproveitar o contéudo de forma satisfatória.
      </p>
    </span>
<div class="clear"></div>
</div>