<div class="center">
  <div class="checkout_content rounded shadow">
    <div id="alert_message" class="fm_alert rounded shadow" style="display:none"></div>
    <p class="content_title">Ganhe um Smartphone Samsung Galaxy S3</p>

    <?php $nome_projeto = ' Anúncio Mosaico '; ?>
    <div>
      <p align="center">
      	<table>
      		<tr>
      			<td>
      				<img src="<?php echo $this->basePath();  ?>/images/app/banner728x200ganhe.jpg"  />
      			</td>
      			<td>
      				<?php //var_dump($this->sessionGanhe->qtd_compradas); //$sessionGanhe = $this->SessionSelection('ganhe');?>

      				<table width="100%" >
      					<tr>
      						<td width="50%" align="right"><?php echo $this->sessionGanhe->qtd_compradas; ?></td>
      						<td>Áreas Compradas</td>
      					</tr>
      					<tr>
      						<td align="right"><?php echo $this->sessionGanhe->qtd_livres; ?></td>
      						<td>Áreas Livres</td>
      					</tr>
      					<tr>
      						<td align="right"><?php echo $this->sessionGanhe->valor_atual; ?></td>
      						<td>Preço Atual</td>
      					</tr>
      					
      				</table>
      			</td>
      		</tr>
      	</table>
      </p>
      
      <p class="afl_title">
        SMARTPHONE I9300 GALAXY SIII BRANCO ANDROID 4.0 / TELA 4.8" / QUAD-CORE 1.4GHZ / CÂMERA 8MP COM FLASH / MEMÓRIA INTERNA 16GB - SAMSUNG
      </p>
      
      <p class="afl_title">Especificações</p>
      
      <p>
     		<table width="100%">
     			<tr>
     				<td width="50%" style="font-size: 10px;">
- Chamada da Operadora: Celular Desbloqueado compatível com todas as operadoras do Brasil<br>
- Marca: Samsung                  <br>
- Sistema: Operacional Android    <br>
- Modelo: Touch                   <br>
- Formato: Barra                  <br>
- Tamanho do Display: 4,8"        <br>
- Tecnologia: 3G                  <br>
- Wi-fi: Sim                      <br>
- Bluetooth: Sim                  <br>
- bluetooth: Sim                  <br>
- Multichip: Não                  <br>
- Câmera: 8MP                     <br>
- Flash: Sim                      <br>
- Câmera Frontal: Sim             <br>
- Filmadora: Full HD              <br>
- câmera filmadora: Sim           <br>
- Sintonizador de TV: sem TV      <br>
- Rádio: FM                       <br>
- radio FM: Sim                   <br>
- GPS: Sim                        <br>
- NFC: Não                        <br>
- Processador: 1.4GHZ             <br>
- Memória Interna: 16GB           <br>
- Quad Core: Sim                  <br>
- Banda: Quadband (850/900/1800/1900 MHZ)<br>
- EDGE: Sim<br>
- GPRS: Sim<br>
- WAP: Sim<br>
- Recursos Fotográficos: LED Flash, Zero Shutter e Câmera Inteligente<br>
- Recursos de videos: Foco, Zoom, Filma em Full HD Câmera Traseira, Filme em HD Câmera Frontal<br>
- MP3 Player: Sim<br>
- Recursos de som: MP3 Player, Tecnologia 3D de Som e Rádio FM<br>
- Extensão para Cartões de Memória: Sim<br>
- Compatibilidade de Cartões de Memória: Micro SD até 64Gb<br>
- Recursos de chamada: Discadas, Perdidas, Atendidas e Direct Call<br>
- Toques: MP3 e Polifônicos<br>
- Alerta vibratório: Sim<br>
- Viva-voz: Sim<br>
- Jogos: Sim. Download no Google Play Store (Android Market)<br>
- Agenda, capacidade máxima de contatos: 1000 contatos variando conforme capacidade interna.<br>
- Data e Horário: Sim<br>
- Calendário: Sim<br>
- Calculadora: Não<br>
- Idiomas do menu: Português, Inglês e Espanhol<br>
- Alimentação, tipo de bateria: Bateria de 2100 mAh<br>
- Conteúdo da Embalagem: Bateria, Carregador de viagem, Manual do usuário, Certificado de garantia, Cabo USB, Fone de Ouvido Estéreo<br>
- Dimensões aproximadas do produto - cm (AxLxP): 13,7x 7,1x 0,8 cm<br>
- Peso liq. aproximado do produto (Kg): 133g<br>
- Garantia do Fornecedor: 12 meses contra defeitos de fabricação<br>
- Mais Informações: Pop Up Play, Smart Stay, Smart Alert e Social Tag<br>
- Referência do modelo: GT-I9300MBLZTO<br>
     				</td>
     				<td valign="top" style="font-weight: 200;">
     					<p class="afl_title">Como funciona?</p>
     					<p>
     						A cada área livre comprada o preço do smartphone galaxy S3 é diminuido.</p> 
							
						<p>	Por exemplo:<br>
							Existem atualmente 500 áreas livres disponiveis 
							para compra. Logo você compra 100 áreas então
							resta 400 áreas livres para você levar o produto.
     					</p>
     					
     					<p class="afl_title">Isto é sorteio?</p>
     					<p>
     						Não, a última pessoa que comprar todas as áreas leva o produto.</p> 
     						
     					<p class="afl_title">Quando o produto for vendido, será apresentado outro?</p>
     					<p>Sim, mas não necessárimente o mesmo produto.</p> 
     					
     					<p class="afl_title">Após comprar todas as áreas, como o produto será entrege?</p>
     					<p>Entraremos em contato por email, informando a entrega do produto. Após nossa equipe receber os dados de endereço o produto será enviado via sedex, junto com a nota fiscal.</p> 
     					
     					<p class="afl_title">O produto é novo?</p>
     					<p>Sim, adquirimos apenas produtos em lojas credenciadas pelo fabricante.</p> 
     					
     					
     				</td>
     			</tr>
     			
     		</table> 	

      </p>
  </div>   
<div class="clear"></div>
</div>