<div class="center">
  <div class="checkout_content rounded shadow">
    <div id="alert_message" class="fm_alert rounded shadow" style="display:none"></div>
    <p class="content_title">PROGRAMA DE AFILIADOS</p>

    <?php $nome_projeto = ' Anúncio Mosaico '; ?>
    <div>
      
      <?php if(!empty($this->dados['url_divulgacao'])): ?>
        <p class="afl_title">Seu link de divulgação é:</p>
        <p class="destaque_my_link" align="center">
         <?php echo $this->dados['url_divulgacao']; ?>
        </p>
      <?php endif; ?>
      
      <p>
        
        Com o Programa de Afiliados <?php echo $nome_projeto; ?> você pode gerar lucros reais para sua conta. É muito simples. Você divulga o link gerado abaixo para seus amigos através das redes sociais, emails, blogs entre outras ações.
        <br> A cada área de 100 pixel (10x10) registrada pelo usuário indicado, você ganha 1 real.
        <br>São 1 milhão de áreas de 100 pixel que você pode oferecer.
      </p>
      
      <p class="afl_title">Como funciona?</p>
      
      <p align="center"><img src="<?php echo $this->basePath();  ?>/images/app/afiliados.jpg"  /></p>
      
      <p class="afl_title">Terei algum custo? Preciso pagar alguma coisa?</p>
      <p>
        Basta criar uma conta e comprar uma área pequena de 100 pixel (10x10). Não é necessário pagar mais nenhuma taxa, mensalidade ou qualquer outro tipo de cobrança.
      </p>
      
      <p class="afl_title">Onde vejo o meu saldo e meus indicados?</p>
      <p>
        Faça login e clique em <b>Minha Conta</b> no menu superior.
        <br>
          Você será direcionado para sua tela alteração de dados e Afiliado que traz todas as informações referentes a sua conta.
          <br><br>
            <ul>
              <li>Seu link de indica&ccedil;&atilde;o</li>
              <li>Quantidade de indicados</li>
              <li>Saldo atual</li>
              <li>Valor total das retiradas</li>
              <li>Dados das contas dos indicados</li>
            </ul>
      </p>
      
      <p class="afl_title">Como é feito o meu pagamento? Qual o valor mínimo?</p>
      <p>
        Pensando em sua segurança, seu pagamento será feito mensalmente através do Sistema de Pagamento Seguro Bcash.
<br><br>
Para receber pelo Bcash, é necessário que você abra uma conta gratuitamente através do link abaixo:
<br><a href="http://www.pagamentodigital.com.br">http://www.bcash.com.br</a>
<br><br>
Sempre que você possuir saldo nesta conta, você poderá fazer a transferência para qualquer conta bancária de sua preferência.
<br><br>
Os pagamentos serão realizados quando seu crédito for igual ou superior a R$ 60,00 (sessenta reais). Caso as quantias creditadas sejam inferiores à soma mencionada anteriormente, aguardar-se-á que a mesma seja atingida para então proceder-se ao pagamento. 
      </p>
      
      <p class="afl_title">Termo de Adesão</p>
      <p>
      <textarea cols=50 rows=10>
        
       Termo de Adesão ao Programa de Afiliados <?php echo $nome_projeto; ?>
CONSIDERANDO que este Termo de Afiliados contém as regras que se aplicam à participação de Pessoas Físicas e Jurídicas no Programa de Afiliados <?php echo $nome_projeto; ?>, doravante chamado de "Programa", onde os visitantes indicados pelo Afiliado poderão comprar áreas livres no tamanho de 100 pixel, através de um link de acesso exclusivo do Afiliado para o site do <?php echo $nome_projeto; ?>,
AS PARTES TÊM ENTRE SI JUSTO E ACERTADO CELEBRAR O PRESENTE TERMO DE AFILIADOS QUE SE REGERÁ PELAS SEGUINTES CLÁUSULAS E CONDIÇÕES:
1. Registro no Programa
1.1. Para participar do Programa basta acessar a página de programa de afiliados e clicar no botão Ativar Programa de Afiliados. 
1.2. Após ser ativado, o Afiliado receberá um e-mail com um link gerado, confirmando que se tornou um Afiliado do <?php echo $nome_projeto; ?>. A partir deste momento, o Afiliado poderá acessar e utilizar os materiais e informações disponíveis na página de afiliados, observando o disposto na cláusula 4 abaixo.
1.3. A Infoca Internet reserva-se o direito de recusar o registro como Afiliado, na hipótese do Afiliado divulgar qualquer material, imagem ou conteúdo que esteja em discordância com as Políticas da Internet Links Interactive, de acordo com o disposto na cláusula 4 abaixo.
2. Venda dos Planos
2.1. A Infoca Internet será a única responsável por processar as vendas das áreas livre feitas pelos indicados do Afiliado, efetuando o registro da venda, o cadastro do comprador, a cobrança e recebimento do preço, e por fim, o registro na área livre.
3. Comissão sobre vendas
3.1. A Infoca Internet pagará as seguintes comissões sobre as vendas realizadas através do Afiliado:
* R$ 1 real de bonificação sobre a área livre de 100 pixel paga para cada cliente indicado pelo Afiliado;
3.2. Todos os valores devidos ao Afiliado, referentes às comissões, serão pagos no 15° (décimo quinto) dia útil do mês subsequente aquele em que faturadas as receitas pela Infoca Internet, desde que estes valores sejam superiores ou iguais a R$60,00 (sessenta reais).
3.3. A Infoca Internet considerará devida a comissão somente após faturados e pagos os pedidos. Para o cálculo da comissão será considerado o período do primeiro ao último dia do mês imediatamente anterior.
3.4. O Afiliado poderá acompanhar as vendas realizadas através da página Minha Conta no item Programa de Afiliados, acessando um relatório exclusivo online mediante a utilização do seu login com e-mail e senha.
3.5. O pagamento das comissões sobre as vendas indicadas pelo Afiliado, será feito através do sistema de pagamentos eletrônico Pagamento Digital. Para isso o Afiliado deverá se cadastrar gratuitamente no Pagamento Digital através do link existente na página de Afiliados da Central do Cliente. Para fins aqui disposto, a Infoca Internet só fará o pagamento ao Afiliado, mediante a apresentação um recibo para pessoas físicas.
Cada parte será responsável pelo recolhimento dos tributos incidentes sobre suas operações e serviços, incluindo aqueles resultantes deste instrumento.
4. Exclusão do Programa
4.1. A Infoca Internet reserva-se o direito de excluir a conta de Afiliado nas seguintes hipóteses:
a) Afiliado que utilizar o código de afiliados para links, URLs, em páginas e imagens não cadastradas e autorizadas no programa de afiliados pela Infoca Internet.
b) Afiliado que utilizar indevidamente o nome, marca, imagens, textos, páginas, mesmo que parcialmente, dos Sites da Infoca Internet, que não tenham sido expressamente autorizados e da forma divulgada pelo programa de afiliados.
c) Afiliado que utilizar da prática de SPAM para divulgação, reenvio de mensagens, entre seus visitantes e/ou usuários.
d) Afiliado que utilizar as URLs, domínios da Infoca Internet para cadastramento em sites de busca, pesquisa, portais, comparações de produtos, dentre outros.
4.1.2. As hipóteses constantes das letras "a", "b", "c", "d" constituirão infrações gravíssimas que acarretarão a imediata exclusão do programa de afiliados, retenção das comissões eventualmente devidas e incidência das medidas judiciais cabíveis e multas, sem prejuízo, ainda, de a Infoca Internet pleitear perdas e danos.
5. Políticas do <?php echo $nome_projeto; ?>
5.1. Qualquer cliente que comprar através do Programa de Afiliados será considerado cliente da Infoca Internet.
5.2. A Infoca Internet poderá alterar as regras e procedimentos da operação de compra a qualquer tempo, a seu exclusivo critério. Os preços das áreas livres, bem como sua disponibilidade estarão sujeitos às variações do mercado.
5.5. Não obstante o já previsto, a Infoca Internet reserva-se o direito de cancelar o registro do Afiliado a qualquer momento durante a vigência do Programa, se considerar que o o Afiliado possui um site na internet e divulga qualquer material, imagem ou conteúdo que:
* promova qualquer material pornográfico;
* promova qualquer forma de violência;
* promova discriminação racial, sexual, social, religiosa, por idade ou por nacionalidade; 
* promova atividades ilegais;
* viole direitos autorais ou de propriedade intelectual.
6. Responsabilidade do Afiliado
6.1. O Afiliado é o único responsável pelo desenvolvimento, operação e manutenção do Site do Afiliado (caso tenha) e por todo o material e informações nele apresentados, não tendo a Infoca Internet qualquer responsabilidade pelas informações divulgadas.
6.2. O Afiliado é responsável por assegurar que a inserção e divulgação de qualquer material não viola ou infringe direitos de terceiros (incluindo, direitos autorais, marcas, e outros direitos de propriedade intelectual e de imagem).
6.3. Para permitir um funcionamento adequado das operações, o Afiliado deverá se certificar de que o "link" do Afiliado esteja correto. A Infoca Internet não será responsável por perdas ocorridas em consequência de má formatação dos links ou devido à sua manutenção, sendo isso responsabilidade do Afiliado.
7. Prazo; Rescisão
7.1. Este Termo de Afiliados terá início na data em que o seu registro no Programa de Afiliados for feito pelo Site e vigorará por prazo indeterminado podendo ser rescindido a qualquer tempo pelo Afiliado ou pela Infoca Internet, com ou sem motivo, através do envio de comunicação por escrito, sendo aceita como válida a comunicação feita por e-mail. 
Caso o afiliado queira cancelar seu registro, o cancelamento será considerado como efetivado na data de envio de comunicação da Infoca Internet ao afiliado. 
No caso em que a Infoca Internet optar por cancelar a conta do afiliado, a comunicação será enviada com 7 (sete) dias de antecedência.
7.2 Não obstante o disposto acima, o Termo de Afiliados poderá ser imediatamente rescindido pela Infoca Internet, sem necessidade de qualquer notificação ao Afiliado, nos casos de (i) violação pelo Afiliado de quaisquer das Políticas da Infoca Internet descritas na cláusula 4 acima, de quaisquer leis ou regulamentos aplicáveis ao Afiliado, inclusive normas de proteção ao consumidor, e (ii) prática pelo Afiliado de quaisquer atos que possam implicar descrédito comercial ou institucional para a Infoca Internet.
7.3. As comissões sobre as vendas das áreas realizadas imediatamente antes do término do mesmo só serão pagas caso os pedidos das áreas em questão não sejam cancelados ou devolvidos, e desde que os preços respectivos tenham sido recebidos pela Infoca Internet.
7.4. A Infoca Internet poderá reter o pagamento das comissões sobre vendas das áreas efetuadas através do Afiliado, após o término deste Termo de Afiliados, pelo prazo de até o décimo quinto dia útil (15o.) do mês subseqüente ao cancelamento, para assegurar que o último pagamento referente às vendas das áreas para os indicados do Afiliado tenha sido efetivado.
7.5. No caso de rescisão o Afiliado não terá direito às demais mensalidades referentes à assinatura dos clientes indicados.
8. Modificação
8.1. A Infoca Internet reserva-se o direito de modificar quaisquer dos termos e condições contidas neste Termo de Afiliados, a qualquer tempo, através da apresentação de um aviso de mudança ou de um novo Termo de Afiliados.
8.2. Em caso de discordância do Afiliado quanto às modificações realizadas no Termo de Afiliados, poderá o Afiliado rescindir este Termo de Afiliados, mediante notificação a Infoca Internet, na forma da cláusula 7.1. acima. Caso o Afiliado continue a participar do Programa de Afiliados após aviso de modificação do mesmo, através do Site da Infoca Internet, isto indicará que o Afiliado aceitou todas as modificações comunicadas.
9. Relacionamento entre as Partes do Programa de Afiliados
9.1. O Afiliado e a Infoca Internet são partes contratantes independentes e nenhum dos termos deste Termo de Afiliados autoriza ou resulta na criação de qualquer sociedade, joint-venture, consórcio, franquia, representação de vendas ou relação de trabalho entre as partes (vínculo empregatício). O Afiliado não tem autorização para aceitar, fazer quaisquer ofertas ou de qualquer forma atuar em nome da Infoca Internet.
9.2. Nenhuma das partes tem qualquer direito, poder ou autoridade de assumir qualquer obrigação ou responsabilidade em nome ou por conta da outra.
9.3. São de exclusiva responsabilidade de cada uma das Partes todas as obrigações relativas à contratação e/ou relacionamento com empregados e contratados que, direta ou indiretamente, lhe prestam ou venham a prestar serviços para execução do presente Contrato, inexistindo entre tais pessoas e a outra Parte, qualquer vínculo de natureza empregatícia ou contratual de qualquer espécie.
9.4. O Afiliado não poderá fazer qualquer afirmação que contradiga qualquer dos termos descritos nesta cláusula, ou em qualquer outro item deste Termo de Afiliados.
10. Responsabilidades da Infoca Internet
10.1. A responsabilidade da Infoca Internet perante seus Afiliados refere-se ao pagamento das comissões sobre as vendas das áreas livres realizadas através do <?php echo $nome_projeto; ?>, conforme descrito no item 3 acima. Além disso, a Infoca Internet será responsável pelo processamento, venda e suporte das áreas, conforme disposto no item 2 acima. A Infoca Internet não será responsável por quaisquer danos, perdas de rendimentos, de lucros ou de informações decorrentes direta ou indiretamente deste Termo de Afiliados.
10.2 A Infoca Internet não será responsável por interrupções ou erros que ocorram na transmissão de dados via Internet.
11. Aceitação dos Termos
O Afiliado declara que avaliou e aceita a sua participação no Programa de Afiliados <?php echo $nome_projeto; ?> e concorda com todos os termos e condições do presente Termo de Afiliados. Reconhece, também, que a Infoca Internet poderá, a qualquer tempo, solicitar referências do mesmo, assim como operar em parceria com outras entidades e indivíduos que atuem na mesma área de negócios.
12. Confidencialidade
As Partes comprometem-se, mutuamente, a zelar pela manutenção do sigilo de todos os segredos comerciais, conhecimentos técnicos e outras informações que venham a tomar conhecimento uma da outra em função do relacionamento comercial de que trata o presente Termo de Afiliados, não podendo usar qualquer dessas informações confidenciais, a não ser quando expressamente autorizadas para tanto por seu titular. Nesse sentido, cada Parte deverá, e para isso exercerá todos os seus poderes, fazer com que seus sócios, empresas afiliadas, administradores, prepostos, empregados e/ou quaisquer outras pessoas sob sua responsabilidade (direta ou indireta) mantenham em sigilo todos os termos e condições do presente Contrato.
13. Disposições Gerais
13.1. O presente Termo constitui o acordo integral entre as Partes, prevalecendo sobre qualquer outro acordo, verbal ou escrito, previamente estabelecido entre as Partes.
13.2. Todos os avisos e demais comunicações aqui exigidos ou permitidos serão por escrito e serão havidos como tendo sido devidamente transmitidos quando entregues em mãos, ou quando despachados por telefax (confirmado por escrito por correspondência simultaneamente encaminhada pelo correio) ao destinatário ou por correio eletrônico (e-mail), com comprovante de recebimento.
13.3. A omissão ou tolerância das Partes, em exigir o estrito cumprimento dos termos e condições deste Termo, não constituirá novação ou renúncia, nem afetará os seus direitos, que poderão ser exercidos a qualquer tempo.
13.4. No caso de qualquer reivindicação ou controvérsia decorrente deste contrato, a ele relacionada ou resultante de sua violação, as Partes envidarão seus melhores esforços para solucionar a questão de forma amigável. Para tanto, as partes negociarão de forma a obter solução que seja justa e satisfatória para elas.
Não chegando as partes a um acordo, fica eleito o foro Central da cidade de São Paulo, Estado de São Paulo, para decidir a referida controvérsia, em prejuízo de qualquer outro, por mais privilegiado que seja.        
      </textarea>
      </p>
      <br>
      
      <?php if(!empty($this->dados['nome_usuario'])): ?>
      <p align="center">
       
        <?php if(!empty($this->dados['url_divulgacao'])): ?>
          Programa de Afiliados está ativo
        <?php else: ?>
        <input type="button" onclick="window.location='{$url_ativa_afiliado}';" name="register" id="register" value="Ativar Programa de Afiliados" class="btn_submit shadow" title="Cadastrar">
        <?php endif; ?>
      </p>
      {else}
      <p align="center" class="afl_ativa">
        Para ativar faça login ou <a href="{$url_cadastro}" >Cadastre-se</a>
      </p>
      <?php endif; ?>
      
  </div>   
<div class="clear"></div>
</div>