<table width="100%" border="0" cellspacing="10" cellpadding="20" bgcolor="#89B657">
<tr>
        <td>
            <table width="700" border="0" align="center" cellpadding="5" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif">
                <tr>
                    <td height="115" bgcolor="#FFFFFF" align="center"><img src="<?php echo $this->serverUrl('/images/logo/logotipo300px.png'); ?>" alt=""></td>
                </tr>
                <tr>
                    <td bgcolor="#333333">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tr>
                                <td width="660" height="25"><span style="font-size:16px;color:#fff;font-weight:bold">
                                    1ª Etapa do cadastro realizada com sucesso </span></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#FFFFFF">
                        <table width="660" border="0" align="center" cellpadding="10" cellspacing="0">
                            <tr>
                                <td width="660">
                                    <p style="font-size:16px;color:#333;font-weight:bold">Olá, </p>
                                    <p style="font-size:16px;color:#333;font-weight:bold"><span style="color:#333;font-size:12px;font-family:Arial,Helvetica,sans-serif">Por favor, clique no link abaixo para continuar seu cadastro.</span> </p>
                                    <p style="font-size:16px;color:#333;font-weight:bold"><span style="color:#333;font-size:12px;font-family:Arial,Helvetica,sans-serif"><a href="<?php echo $this->serverUrl($this->url('register/step2', array('token' => $this->dados['token']))); ?>"><?php echo $this->serverUrl($this->url('register/step2', array('token' => $this->dados['token']))); ?></a>
</span> </p>

                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td height="35" bgcolor="#EDEDED">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tr>
                                <td width="660"><span style="font-size:12px;color:#999;font-weight:bold">
                                </span></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <br>
            <br>
        </td>
    </tr>
</table>

