<div class="center">
<div class="content rounded shadow">
        <p class="content_title">FAQ (Perguntas Frequentes)</p>

    
          <div class="answer">
              <p class="faq_title"><a href="javascript:void(0);">1) Como faço para comprar as áreas livres do site?</a></p>
              <p class="faq_desc">Faça login, e selecione algum botão na parte superior do site como R$ 3,00, R$ 6,00 entre outros. Você será redirecionado para página do Pagamento Digital, siga os procedimentos de cadastro e selecione a forma de pagamento desejado. 
<br>Após o sistema pagseguro confirmar seu pagamento, será creditado o valor em sua conta.
<br>Selecione as áreas livres desejadas e clique no botão comprar na parte superior do site. 
<br>No carrinho será listadas as áreas selecionadas clique no botão finalizar compra.</p>
          </div>
  
          <div class="answer">
              <p class="faq_title"><a href="javascript:;">2) Como faço para alterar a imagem da minha área?</a></p>
              <p class="faq_desc">Faça login e clique na sua área, sinalizada com a imagem M. 
Em Editar Área, selecione uma imagem do seu computador no tamanho máximo de 500kb. Após sua imagem ser exibida selecione a área desejada, em 100 pixels. 
Verifique a área selecionada e clique no botão Editar para confirmar.</p>
          </div>
          
          <div class="answer">
              <p class="faq_title"><a href="javascript:;">3) Como faço para alterar título e url da minha área?</a></p>
              <p class="faq_desc">Faça login e clique na sua área, sinalizada com a imagem M. 
Em Editar Área preecha os campos Título e URL(sem http://). Clique no botão Editar para confirmar.         </div>
          
          <div class="answer">
              <p class="faq_title"><a href="javascript:;">4) O que é Pagamento Digital?</a></p>
              <p class="faq_desc">Pagamento Digital é uma ferramenta de pagamentos online, um facilitador de pagamentos para transações comerciais pela internet. Com esta ferramenta lojas ou pessoas que tenham interesse em efetuar vendas na internet podem criar uma conta e receber pagamentos através desta ferramenta. </p>
          </div>
          
         
        
      <div class="clear"></div>

    </div>
</div>