<table width="100%" border="0" cellspacing="10" cellpadding="20" bgcolor="#498F99">
    <tbody><tr>
        <td>
            <table width="700" border="0" align="center" cellpadding="5" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif">
                <tbody><tr>
                    <td height="115" bgcolor="#FFFFFF"><img src="<?php echo $this->serverUrl('/images/logo/logotipo300px.png'); ?>" alt=""></td>
                </tr>
                <tr>
                    <td bgcolor="#333333">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="660" height="25"><span style="font-size:20px;color:#ffffff;font-weight:bold">
                                    Formulário Fale Conosco                             </span></td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#FFFFFF">
                        <table width="660" border="0" align="center" cellpadding="10" cellspacing="0">
                            <tbody><tr>
                                <td width="660">
                                    <p style="font-size:16px;color:#333;font-weight:bold">Nome: <?php echo $this->dados['nome']; ?> </p>
                                    <p style="font-size:16px;color:#333;font-weight:bold">Email: <?php echo $this->dados['emailfc']; ?> </p>
                                    <p style="font-size:16px;color:#333;font-weight:bold">Message: <?php echo $this->dados['msg']; ?> </p>

                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr>
                    <td height="35" bgcolor="#EDEDED">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="660"><span style="font-size:12px;color:#999;font-weight:bold">
                                    <?php echo $this->serverUrl(); ?>                                    <br>
                                </span></td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
            <br>
            <br>
        </td>
    </tr>
</tbody></table>