<table width="100%" border="0" cellspacing="10" cellpadding="20" bgcolor="#498F99">
    <tbody><tr>
        <td>
            <table width="700" border="0" align="center" cellpadding="5" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif">
                <tbody><tr>
                    <td height="115" bgcolor="#FFFFFF"><img src="<?php echo $this->serverUrl('/images/app/logo/logotipo300px.png'); ?>" alt=""></td>
                </tr>
                <tr>
                    <td bgcolor="#333333">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="660" height="25"><span style="font-size:20px;color:#ffffff;font-weight:bold">
                                    Redefinição de Senha                             </span></td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#FFFFFF">
                        <table width="660" border="0" align="center" cellpadding="10" cellspacing="0">
                            <tbody><tr>
                                <td width="660">
                                    <p style="font-size:16px;color:#333;font-weight:bold">Olá <?php echo $this->dados['nome']; ?> </p>
                                    <p style="font-size:16px;color:#333;font-weight:bold"><span style="color:#333;font-size:12px;font-family:Arial,Helvetica,sans-serif"> Esqueceu a sua senha? Sem problemas, acontece!<br>Utilize o link abaixo para redefiní-la: </span></p>
                                    <table width="640" border="0" align="center" cellpadding="10" cellspacing="0" style="border:1px solid #ccc">
                                        <tbody><tr>
                                            <td bgcolor="#FFFFFF"><span style="font-size:14px;font-weight:bold"><a href="<?php echo $this->serverUrl($this->url('changepassword',array('email'=>$this->dados['email'],'token'=>$this->dados['token']))); ?>" style="color:#f90" target="_blank">Redefinir senha</a></span></td>
                                        </tr>
                                    </tbody></table>
                                    <p><span style="color:#333;font-size:12px;font-family:Arial,Helvetica,sans-serif"><strong>Caso tenha recebido esse e-mail por engano, você não precisa tomar nenhuma providência e pode desconsiderá-lo.</strong></span></p>
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr>
                    <td height="35" bgcolor="#EDEDED">
                        <table width="660" border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="660"><span style="font-size:12px;color:#999;font-weight:bold">
                                    <?php echo $this->serverUrl(); ?>                                    <br>
                                </span></td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
            <br>
            <br>
        </td>
    </tr>
</tbody></table>