<div class="center">
  <div class="checkout_content rounded shadow">
    <div id="alert_message" class="fm_alert rounded shadow" style="display:none"></div>
    <p class="content_title">EDITAR ÁREA</p>
    <p style="text-align: center;">Upload -> <span style="font-weight: bold;">Seleção</span> -> Confirmação</p>
    <p style="margin: 10px 0 10px 0;text-align: center;">Selecione abaixo uma área (10x10=100 pixels) da imagem enviada:</p>
    	<div style="text-align: center;">

		    <?php
		    
			    $size_area = 10;
			    $c_left = 0;
			    $c_top = 0;
			    $c_btn = $size_area;
			    //$area_total = ($this->dados['width']*$this->dados['height']);
				$area_total = 10000;
				$list_area_image = "";
			    for($qtd_total = 1;$qtd_total <= $area_total;$qtd_total++){
			      
			      $v_left = $c_left;
			      $v_top = $c_top;
			      $v_right = $c_left+$size_area;
			      $v_btn = $c_btn;
			      $area_seq =  $v_left.$v_top.$v_right.$v_btn;
			      $area_title= "Clique aqui para selecionar esta área: ".$v_left.','.$v_top.','.$v_right.','.$v_btn;
			      $codfica = urlencode(base64_encode($v_left.','.$v_top.','.$v_right.','.$v_btn));
			  
			      //$url_area = url_secure("index.php?pag=editar_area&r=".$codfica."&a=".$_GET['a']);
			      $url_area = $this->url('area-edit',array('action'=>'step3','area'=>$dados['area'],'area-sel'=>$codfica));
			      $list_area_image .= '<area  shape="rect" coords="'.$v_left.','.$v_top.','.$v_right.','.$v_btn.'" href="'.$url_area.'" title="'.$area_title.'" />';
			       
			      if($v_right < 1000)
			        $c_left = $c_left + $size_area;
			      else{
			        $c_top = $c_top + $size_area;
			        $c_btn = $c_btn + $size_area;
			        $c_left = 0;
			      }
			    }
		    ?>
	
			<img src="<?php echo $this->url('area-edit-myimg'); ?>" class="maph" usemap="#image_submit_map"  /><map name="image_submit_map"><?php echo $list_area_image; ?></map>
		
		   	<script type="text/javascript">
			    $(function() {
			      $('.maph').maphilight();
			    });
		  	</script>
		</div>
		<p style="text-align: center;"><input type="button" value="Remover imagem" class="btn_submit shadow" onclick="window.location='<?php echo $this->url("area-edit",array('area'=>$this->dados['area'],'action'=>'rmimg'));?>';"  /></p>
	</div>  
	<div class="clear"></div>
	<div class="clear"></div>
</div>

