	  <?php
	  	//var_dump($this->array_records_all);exit;
		$sessionCarrinho = $this->SessionSelection('carrinho');
		$itens_carrinho = $sessionCarrinho->areas;
	    $ar_id_areas = array();
		if(!empty($itens_carrinho)){
			foreach($itens_carrinho as $k => $v){
				$ar_id_areas[] = $v['id_area'];	
			}
		}
		
		$size_area = 10;
        $c_left = 0;
        $c_top = 0;
        $c_btn = $size_area;
        $area_total = 10000;
            
        $sessionUser = $this->UserIdentity('Login');
		
        for($qtd_total = 1;$qtd_total <= $area_total;$qtd_total++){
        
            $v_left = $c_left;
            $v_top = $c_top;
            $v_right = $c_left+$size_area;
            $v_btn = $c_btn;
            $area_seq =  $v_left.$v_top.$v_right.$v_btn;
			$area_target = "";
            
            $codfica = urlencode(base64_encode($v_left.','.$v_top.','.$v_right.','.$v_btn));
            if($sessionUser){
            	$url_area 	= $this->url('area-add',array('area'=>$codfica));
				$area_title = "Área Livre: Clique aqui para registrar";
			}else{
				$area_title = "Faça seu login ou cadastre-se para registrar esta área";
				$url_area 	= "";
			}
			
            
		    if(is_array($ar_id_areas))
		    {
		    	if(in_array($area_seq,$ar_id_areas)){
			      	$url_area 	= $this->url('area-remove',array('area'=>$codfica));
	    			$area_title = "Clique aqui para remover a área do carrinho";
			    } 
		    }
			
			
            if(!empty($this->array_records_all[$area_seq]['seq_coord']) &&
               $area_seq == $this->array_records_all[$area_seq]['seq_coord']){
            
				if($sessionUser['user']->id == $this->array_records_all[$area_seq]['id_user'])
				{
					$url_area 	= $this->url('area-edit',array('area'=>$codfica, 'action' => 'step3'));
	                $area_title = "Clique aqui para editar está área \nTitulo: ".$this->array_records_all[$area_seq]['titulo']."\nURL: ".$this->array_records_all[$area_seq]['url'];
			        $onmouseover = "modo_area('over','id".$area_seq."',this)";
			        $onmouseout = "modo_area('out','id".$area_seq."',this)";
				}else{
					$url_area = $this->array_records_all[$area_seq]['url'];
	                $area_title = (empty($url_area) && empty($this->array_records_all[$area_seq]['titulo'])) ? 'Área Registrada' : $this->array_records_all[$area_seq]['titulo']."\n".$url_area;
	                $onmouseover = '';
	                $onmouseout = '';
				}
            }else{
                $onmouseover = '';
                $onmouseout = '';
            }
			
			if(!empty($url_area) && !empty($url_area)){
				if(strpos($url_area, "http://") === false && empty($onmouseover) && !$sessionUser){
					$url_area = "http://".$url_area;
				}
				$str_link = "href='$url_area'";
				if(!$sessionUser)
					$str_target = "target='_blank'";
			}else{
				$str_link = "";
				$str_target = "";
			}
            
            echo $list_areas = '<area id="id'.$area_seq.'" class="area_style" onmouseover="'.$onmouseover.'" onmouseout="'.$onmouseout.'" shape="rect" coords="'.$v_left.','.$v_top.','.$v_right.','.$v_btn.'" '.$str_link.' title="'.$area_title.'" '.$str_target.' />'. PHP_EOL;
            
            if($v_right < 1000)
                $c_left = $c_left + $size_area;
            else{
                $c_top = $c_top + $size_area;
                $c_btn = $c_btn + $size_area;
                $c_left = 0;
            }
        
        }
		
	  ?>
